/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef checklicense_CONSTANTS_H
#define checklicense_CONSTANTS_H

#include "checklicense_types.h"



class checklicenseConstants {
 public:
  checklicenseConstants();

};

extern const checklicenseConstants g_checklicense_constants;



#endif
