/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "checklicense_constants.h"



const checklicenseConstants g_checklicense_constants;

checklicenseConstants::checklicenseConstants() {
}



